version: '3.5'

services:
  forsage-ui:
    container_name: forsage-ui
    image: forsage-ui
    build:
      context: ./
      target: forsage-ui
    networks:
      - forsage
    command: >
      bash -c "ng serve --disable-host-check --host 0.0.0.0 --port 4200"
  forsage-nginx:
    container_name: forsage-nginx
    image: forsage-nginx
    build:
      context: ./
      target: forsage-nginx
    networks:
      - forsage
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./dist:/usr/src/app/dist
    ports:
      - '80:80'

networks:
  forsage:
    external: true